[package]
name = "sea-orm-axum-example"
version = "0.1.0"
authors = ["Yoshiera Huang <huangjasper@126.com>"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "service", "entity", "migration"]

[dependencies]
axum-example-api = { path = "api" }
sea-orm = { version = "~2.0.0-rc", features = ["runtime-tokio-rustls", "macros", "debug-print"] }
seaography = { version = "~2.0.0-rc", features = ["with-decimal", "with-chrono", "with-uuid", "field-snake-case"] }

[patch.crates-io]
sea-orm = { git = "https://github.com/SeaQL/sea-orm", branch = "master" }
sea-orm-migration = { git = "https://github.com/SeaQL/sea-orm", branch = "master" }
seaography = { git = "https://github.com/SeaQL/seaography", branch = "main" }