//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "advertisements")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub link: Option<String>,
    pub filename: Option<String>,
    pub day_count: i32,
    pub total_count: i32,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
    pub genres: Option<String>,
    pub sub_genres: Option<String>,
    pub states: Option<String>,
    pub countries: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
