//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "album_aliases")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub album_id: u32,
    #[sea_orm(unique_key = "alias_key_unique")]
    pub band_id: u32,
    #[sea_orm(unique_key = "alias_key_unique")]
    pub radio_station_id: Option<u32>,
    #[sea_orm(unique_key = "alias_key_unique")]
    pub alias_key: String,
    pub slug: Option<String>,
    pub sanitized_name: Option<String>,
    pub soundex_key: Option<String>,
    pub phonetic_key: Option<String>,
    pub metaphone_key: Option<String>,
    pub dmetaphone_key: Option<String>,
    pub dmetaphone_alt_key: Option<String>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id"
    )]
    Album,
    #[sea_orm(
        belongs_to = "super::bands::Entity",
        from = "Column::BandId",
        to = "super::bands::Column::Id"
    )]
    Band,
    #[sea_orm(
        belongs_to = "super::radio_stations::Entity",
        from = "Column::RadioStationId",
        to = "super::radio_stations::Column::Id"
    )]
    RadioStation,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Album.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Band.def()
    }
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
