//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "album_rankings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub album_id: Option<u32>,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub category: Option<String>,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub chart_slug: Option<String>,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub term: Option<String>,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub limit: i32,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub start: Option<String>,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub finish: Option<String>,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub rank: i32,
    #[sea_orm(unique_key = "unique_album_chart")]
    pub lw_rank: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id"
    )]
    Album,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Album.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
