//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize, ToSchema)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub label_id: Option<u32>,
    pub name: Option<String>,
    pub slug: Option<String>,
    pub release_date: Option<Date>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub about: Option<String>,
    #[sea_orm(
        column_type = "custom(\"MEDIUMTEXT\")",
        nullable
    )]
    pub thanks: Option<String>,
    pub producer: Option<String>,
    pub engineer: Option<String>,
    pub studio: Option<String>,
    pub master: Option<String>,
    pub itunes_url: Option<String>,
    pub cdbaby_url: Option<String>,
    pub amazon_url: Option<String>,
    pub img: Option<String>,
    pub itunes_id: Option<u32>,
    pub rovi_id: Option<String>,
    pub sub_genre_for_charting: Option<u32>,
    pub genre_admin_set: i8,
    pub compilation: i8,
    pub soundtrack: i8,
    pub approved: i8,
    pub approved_by: Option<u32>,
    pub verified: i8,
    pub verified_by: Option<u32>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,

    // New format field
    /// Album format: "lp", "ep", or "single"
    pub format: String,

    // New status fields
    /// Data status: "new", "validated", "needs_review", "duplicate_detected"
    pub data_status: String,
    /// Reason for data status change
    pub data_status_reason: Option<String>,
    /// Note about data status
    #[sea_orm(column_type = "Text", nullable)]
    pub data_status_note: Option<String>,
    /// When data status was last changed
    pub data_status_at: Option<DateTime>,
    /// User who changed data status
    pub data_status_by: Option<u32>,

    /// Chart status: "pending", "approved", "denied", "suspended"
    pub chart_status: String,
    /// Reason for chart denial: "duplicate", "terms_violation", "editorial", "spam", "other"
    pub chart_denial_reason: Option<String>,
    /// Note about chart status
    #[sea_orm(column_type = "Text", nullable)]
    pub chart_status_note: Option<String>,
    /// When chart status was last changed
    pub chart_status_at: Option<DateTime>,
    /// User who changed chart status
    pub chart_status_by: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_images::Entity")]
    AlbumImages,
    #[sea_orm(
        belongs_to = "super::labels::Entity",
        from = "Column::LabelId",
        to = "super::labels::Column::Id"
    )]
    Label,
    #[sea_orm(
        belongs_to = "super::sub_genres::Entity",
        from = "Column::SubGenreForCharting",
        to = "super::sub_genres::Column::Id"
    )]
    SubGenre,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id"
    )]
    Approver,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::VerifiedBy",
        to = "super::users::Column::Id"
    )]
    Verifier,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(has_many = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(has_many = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::album_rankings::Entity")]
    AlbumRankings,
    #[sea_orm(has_many = "super::album_total_stats::Entity")]
    AlbumTotalStats,
    #[sea_orm(has_many = "super::album_weekly_stats::Entity")]
    AlbumWeeklyStats,
    #[sea_orm(has_many = "super::album_aliases::Entity")]
    AlbumAliases,
    #[sea_orm(has_many = "super::temp_album_total_stats::Entity")]
    TempAlbumTotalStats,
    #[sea_orm(has_many = "super::albums_songs::Entity")]
    AlbumsSongs,
    #[sea_orm(has_many = "super::albums_bands::Entity")]
    AlbumsBands,
    #[sea_orm(has_many = "super::albums_sub_genres::Entity")]
    AlbumsSubGenres,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::DataStatusBy",
        to = "super::users::Column::Id"
    )]
    DataStatusUser,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ChartStatusBy",
        to = "super::users::Column::Id"
    )]
    ChartStatusUser,
}

impl Related<super::albums_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsSongs.def()
    }
}

impl Related<super::labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Label.def()
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubGenre.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Approver.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_bands::Relation::Bands.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_bands::Relation::Albums.def().rev())
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_songs::Relation::Songs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_songs::Relation::Albums.def().rev())
    }
}

impl Related<super::album_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumImages.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::radio_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylists.def()
    }
}

impl Related<super::radio_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylistArchives.def()
    }
}

impl Related<super::album_rankings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumRankings.def()
    }
}

impl Related<super::album_total_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumTotalStats.def()
    }
}

impl Related<super::album_weekly_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumWeeklyStats.def()
    }
}

impl Related<super::album_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumAliases.def()
    }
}

impl Related<super::temp_album_total_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TempAlbumTotalStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
