//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "articles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub category_id: Option<u32>,
    pub sub_genre_id: Option<u32>,
    pub user_id: Option<u32>,
    #[sea_orm(unique)]
    pub title: Option<String>,
    #[sea_orm(unique)]
    pub slug: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub content: Option<String>,
    pub approved: i8,
    pub approved_by: Option<u32>,
    pub edited_by: Option<u32>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id"
    )]
    Category,
    #[sea_orm(
        belongs_to = "super::sub_genres::Entity",
        from = "Column::SubGenreId",
        to = "super::sub_genres::Column::Id"
    )]
    SubGenre,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    Author,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id"
    )]
    Approver,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::EditedBy",
        to = "super::users::Column::Id"
    )]
    Editor,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubGenre.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Author.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::articles_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::articles_tags::Relation::Articles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
