//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "band_contact")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub band_id: Option<u32>,
    pub email: Option<String>,
    pub first_time_on_chart: i8,
    pub above_30: i8,
    pub above_20: i8,
    pub above_10: i8,
    pub last_rank: i32,
    pub chart_rank_on: i32,
    pub dont_contact: i8,
    pub last_contacted: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bands::Entity",
        from = "Column::BandId",
        to = "super::bands::Column::Id"
    )]
    Band,
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Band.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
