//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "band_links")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub band_id: Option<u32>,
    pub link: Option<String>,
    pub r#type: Option<String>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bands::Entity",
        from = "Column::BandId",
        to = "super::bands::Column::Id"
    )]
    Band,
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Band.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
