//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize, ToSchema)]
#[sea_orm(table_name = "bands")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub city_id: Option<u32>,
    pub country_id: Option<u32>,
    pub state_id: Option<u32>,
    pub name: String,
    pub slug: Option<String>,
    pub website: Option<String>,
    pub email: Option<String>,
    pub twitter: Option<String>,
    pub facebook_url: Option<String>,
    pub lastfm_url: Option<String>,
    pub myspace_url: Option<String>,
    pub bandcamp_url: Option<String>,
    pub wikipedia_url: Option<String>,
    pub cdbaby_url: Option<String>,
    pub youtube_url: Option<String>,
    pub reverb_url: Option<String>,
    pub itunes_url: Option<String>,
    pub instagram_url: Option<String>,
    pub pinterest_url: Option<String>,
    pub itunes_id: Option<u32>,
    pub amg_id: Option<u32>,
    pub rovi_id: Option<String>,
    pub echo_id: Option<String>,
    pub seven_digital_id: Option<u32>,
    pub discogs_id: Option<u32>,
    pub spotify_id: Option<String>,
    pub rdio_id: Option<u32>,
    pub rss_feed: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub bio: Option<String>,
    pub verified: i8,
    pub verified_by: Option<u32>,
    pub approved: i8,
    pub approved_by: Option<u32>,
    pub reviewed_by: Option<u32>,
    pub hot_download: i8,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,

    // New type field
    /// Band type: "artist", "group", or "collaboration"
    pub band_type: String,

    // New status fields
    /// Data status: "new", "validated", "needs_review", "duplicate_detected"
    pub data_status: String,
    /// Reason for data status change
    pub data_status_reason: Option<String>,
    /// Note about data status
    #[sea_orm(column_type = "Text", nullable)]
    pub data_status_note: Option<String>,
    /// When data status was last changed
    pub data_status_at: Option<DateTime>,
    /// User who changed data status
    pub data_status_by: Option<u32>,

    /// Chart status: "pending", "approved", "denied", "suspended"
    pub chart_status: String,
    /// Reason for chart denial: "duplicate", "terms_violation", "editorial", "spam", "other"
    pub chart_denial_reason: Option<String>,
    /// Note about chart status
    #[sea_orm(column_type = "Text", nullable)]
    pub chart_status_note: Option<String>,
    /// When chart status was last changed
    pub chart_status_at: Option<DateTime>,
    /// User who changed chart status
    pub chart_status_by: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cities::Entity",
        from = "Column::CityId",
        to = "super::cities::Column::Id"
    )]
    City,
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id"
    )]
    Country,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::Id"
    )]
    State,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::VerifiedBy",
        to = "super::users::Column::Id"
    )]
    Verifier,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id"
    )]
    Approver,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ReviewedBy",
        to = "super::users::Column::Id"
    )]
    Reviewer,
    #[sea_orm(has_many = "super::band_images::Entity")]
    BandImages,
    #[sea_orm(has_many = "super::band_links::Entity")]
    BandLinks,
    #[sea_orm(has_many = "super::band_contact::Entity")]
    BandContact,
    #[sea_orm(has_many = "super::band_aliases::Entity")]
    BandAliases,
    #[sea_orm(has_many = "super::songs::Entity")]
    Songs,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(has_many = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(has_many = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(has_many = "super::radio_raw_datas::Entity")]
    RadioRawDatas,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffMemberPlaylists,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffMemberPlaylistArchives,
    #[sea_orm(has_many = "super::album_aliases::Entity")]
    AlbumAliases,
    #[sea_orm(has_many = "super::song_aliases::Entity")]
    SongAliases,
    #[sea_orm(has_many = "super::albums_bands::Entity")]
    AlbumsBands,
    #[sea_orm(has_many = "super::bands_sub_genres::Entity")]
    BandsSubGenres,
    #[sea_orm(has_many = "super::bands_users::Entity")]
    BandsUsers,
    #[sea_orm(has_many = "super::song_artists::Entity")]
    SongArtists,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::DataStatusBy",
        to = "super::users::Column::Id"
    )]
    DataStatusUser,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ChartStatusBy",
        to = "super::users::Column::Id"
    )]
    ChartStatusUser,
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::City.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Country.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::State.def()
    }
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_bands::Relation::Albums.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_bands::Relation::Bands.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_users::Relation::Bands.def().rev())
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_sub_genres::Relation::SubGenres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_sub_genres::Relation::Bands.def().rev())
    }
}

impl Related<super::band_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandImages.def()
    }
}

impl Related<super::band_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandLinks.def()
    }
}

impl Related<super::band_contact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandContact.def()
    }
}

impl Related<super::band_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandAliases.def()
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::radio_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylists.def()
    }
}

impl Related<super::radio_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylistArchives.def()
    }
}

impl Related<super::radio_raw_datas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioRawDatas.def()
    }
}

impl Related<super::album_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumAliases.def()
    }
}

impl Related<super::song_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongAliases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
