//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "chart_functions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub compiled_radio_spins: i8,
    pub archived_playlist: i8,
    pub totaled_song_stats: i8,
    pub totaled_album_stats: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
