//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "cities_postal_codes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub city_id: Option<u32>,
    pub postal_code_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cities::Entity",
        from = "Column::CityId",
        to = "super::cities::Column::Id"
    )]
    Cities,
    #[sea_orm(
        belongs_to = "super::postal_codes::Entity",
        from = "Column::PostalCodeId",
        to = "super::postal_codes::Column::Id"
    )]
    PostalCodes,
}

impl ActiveModelBehavior for ActiveModel {}
