//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, ToSchema)]
#[sea_orm(table_name = "genres")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub name: Option<String>,
    pub slug: Option<String>,
    pub chart: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sub_genres::Entity")]
    SubGenres,
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubGenres.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
