//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, ToSchema)]
#[sea_orm(table_name = "postal_codes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub country_id: Option<u32>,
    pub state_id: Option<u32>,
    pub code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id"
    )]
    Country,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::Id"
    )]
    State,
    #[sea_orm(has_many = "super::radio_addresses::Entity")]
    RadioAddresses,
    #[sea_orm(has_many = "super::staff_addresses::Entity")]
    StaffAddresses,
    #[sea_orm(has_many = "super::user_addresses::Entity")]
    UserAddresses,
}

impl Related<super::radio_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioAddresses.def()
    }
}

impl Related<super::staff_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffAddresses.def()
    }
}

impl Related<super::user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAddresses.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Country.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::State.def()
    }
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        super::cities_postal_codes::Relation::Cities.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cities_postal_codes::Relation::PostalCodes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
