//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "radio_internet_details")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub radio_station_id: Option<u32>,
    pub start_time: Option<Time>,
    pub end_time: Option<Time>,
    pub visitors: i64,
    pub hits: i64,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::radio_stations::Entity",
        from = "Column::RadioStationId",
        to = "super::radio_stations::Column::Id"
    )]
    RadioStation,
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
