//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "radio_syndicated_stations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub radio_syndicated_detail_id: Option<u32>,
    pub call_letters: Option<String>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::radio_syndicated_details::Entity",
        from = "Column::RadioSyndicatedDetailId",
        to = "super::radio_syndicated_details::Column::Id"
    )]
    RadioSyndicatedDetail,
}

impl Related<super::radio_syndicated_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioSyndicatedDetail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
