//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "radio_stations_sub_genres")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique_key = "Unique Assoc")]
    pub radio_station_id: Option<u32>,
    #[sea_orm(unique_key = "Unique Assoc")]
    pub sub_genre_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::radio_stations::Entity",
        from = "Column::RadioStationId",
        to = "super::radio_stations::Column::Id"
    )]
    RadioStations,
    #[sea_orm(
        belongs_to = "super::sub_genres::Entity",
        from = "Column::SubGenreId",
        to = "super::sub_genres::Column::Id"
    )]
    SubGenres,
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStations.def()
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubGenres.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
