//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize, ToSchema)]
#[sea_orm(table_name = "radio_stations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: Option<String>,
    pub slug: Option<String>,
    pub r#type: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub info: Option<String>,
    pub approved: i8,
    pub verified: i8,
    pub automatic: i8,
    pub active: i8,
    #[sea_orm(column_type = "Float")]
    pub influence: f32,
    pub no_show: i8,
    pub imported_from_file: i8,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,

    // New status fields
    /// Data status: "new", "validated", "needs_review", "duplicate_detected"
    pub data_status: String,
    /// Reason for data status change
    pub data_status_reason: Option<String>,
    /// Note about data status
    #[sea_orm(column_type = "Text", nullable)]
    pub data_status_note: Option<String>,
    /// When data status was last changed
    pub data_status_at: Option<DateTime>,
    /// User who changed data status
    pub data_status_by: Option<u32>,

    /// Chart status: "pending", "approved", "denied", "suspended"
    pub chart_status: String,
    /// Reason for chart denial: "duplicate", "terms_violation", "editorial", "spam", "other"
    pub chart_denial_reason: Option<String>,
    /// Note about chart status
    #[sea_orm(column_type = "Text", nullable)]
    pub chart_status_note: Option<String>,
    /// When chart status was last changed
    pub chart_status_at: Option<DateTime>,
    /// User who changed chart status
    pub chart_status_by: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::radio_addresses::Entity")]
    RadioAddresses,
    #[sea_orm(has_many = "super::radio_emails::Entity")]
    RadioEmails,
    #[sea_orm(has_many = "super::radio_images::Entity")]
    RadioImages,
    #[sea_orm(has_many = "super::radio_links::Entity")]
    RadioLinks,
    #[sea_orm(has_many = "super::radio_phone_numbers::Entity")]
    RadioPhoneNumbers,
    #[sea_orm(has_many = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(has_many = "super::radio_affiliates::Entity")]
    RadioAffiliates,
    #[sea_orm(has_one = "super::radio_internet_details::Entity")]
    RadioInternetDetails,
    #[sea_orm(has_one = "super::radio_satellite_details::Entity")]
    RadioSatelliteDetails,
    #[sea_orm(has_one = "super::radio_syndicated_details::Entity")]
    RadioSyndicatedDetails,
    #[sea_orm(has_one = "super::radio_terrestrial_details::Entity")]
    RadioTerrestrialDetails,
    #[sea_orm(has_many = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(has_many = "super::radio_raw_datas::Entity")]
    RadioRawDatas,
    #[sea_orm(has_many = "super::staff_members::Entity")]
    StaffMembers,
    #[sea_orm(has_many = "super::album_aliases::Entity")]
    AlbumAliases,
    #[sea_orm(has_many = "super::band_aliases::Entity")]
    BandAliases,
    #[sea_orm(has_many = "super::label_aliases::Entity")]
    LabelAliases,
    #[sea_orm(has_many = "super::song_aliases::Entity")]
    SongAliases,
    #[sea_orm(has_many = "super::radio_stations_sub_genres::Entity")]
    RadioStationsSubGenres,
    #[sea_orm(has_many = "super::radio_stations_users::Entity")]
    RadioStationsUsers,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::DataStatusBy",
        to = "super::users::Column::Id"
    )]
    DataStatusUser,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ChartStatusBy",
        to = "super::users::Column::Id"
    )]
    ChartStatusUser,
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_sub_genres::Relation::SubGenres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::radio_stations_sub_genres::Relation::RadioStations.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::radio_stations_users::Relation::RadioStations.def().rev())
    }
}

impl Related<super::radio_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioAddresses.def()
    }
}

impl Related<super::radio_emails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioEmails.def()
    }
}

impl Related<super::radio_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioImages.def()
    }
}

impl Related<super::radio_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioLinks.def()
    }
}

impl Related<super::radio_phone_numbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPhoneNumbers.def()
    }
}

impl Related<super::radio_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylists.def()
    }
}

impl Related<super::radio_affiliates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioAffiliates.def()
    }
}

impl Related<super::radio_internet_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioInternetDetails.def()
    }
}

impl Related<super::radio_satellite_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioSatelliteDetails.def()
    }
}

impl Related<super::radio_syndicated_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioSyndicatedDetails.def()
    }
}

impl Related<super::radio_terrestrial_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioTerrestrialDetails.def()
    }
}

impl Related<super::radio_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylistArchives.def()
    }
}

impl Related<super::radio_raw_datas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioRawDatas.def()
    }
}

impl Related<super::staff_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMembers.def()
    }
}

impl Related<super::album_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumAliases.def()
    }
}

impl Related<super::band_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandAliases.def()
    }
}

impl Related<super::label_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelAliases.def()
    }
}

impl Related<super::song_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongAliases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
