//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub name: Option<String>,
    pub super_admin_access: i8,
    pub admin_access: i8,
    pub writer_access: i8,
    pub radio_access: i8,
    pub reporter_access: i8,
    pub gold_access: i8,
    pub silver_access: i8,
    pub free_access: i8,
    pub single_artist: i8,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
    #[sea_orm(has_many = "super::permissions::Entity")]
    Permissions,
    #[sea_orm(has_many = "super::roles_system_notes::Entity")]
    RolesSystemNotes,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permissions.def()
    }
}

impl Related<super::system_notes::Entity> for Entity {
    fn to() -> RelationDef {
        super::roles_system_notes::Relation::SystemNote.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::roles_system_notes::Relation::Role.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
