//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "roles_system_notes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub role_id: Option<u32>,
    pub system_note_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RoleId",
        to = "super::roles::Column::Id"
    )]
    Role,
    #[sea_orm(
        belongs_to = "super::system_notes::Entity",
        from = "Column::SystemNoteId",
        to = "super::system_notes::Column::Id"
    )]
    SystemNote,
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl Related<super::system_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemNote.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
