//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "song_rankings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub song_id: Option<u32>,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub category: Option<String>,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub chart_slug: Option<String>,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub term: Option<String>,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub limit: i32,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub start: Option<String>,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub finish: Option<String>,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub rank: i32,
    #[sea_orm(unique_key = "unique_song_chart")]
    pub lw_rank: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::songs::Entity",
        from = "Column::SongId",
        to = "super::songs::Column::Id"
    )]
    Song,
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Song.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
