//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize, ToSchema)]
#[sea_orm(table_name = "songs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub band_id: Option<u32>,
    pub sub_genre_id: Option<u32>,
    pub name: Option<String>,
    pub slug: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub lyrics: Option<String>,
    pub lyrics_writer: Option<String>,
    pub music_writer: Option<String>,
    pub license: Option<String>,
    pub publisher: Option<String>,
    pub length: u64,
    pub release_date: Option<Date>,
    pub itunes_url: Option<String>,
    pub itunes_img: Option<String>,
    pub itunes_preview: Option<String>,
    pub itunes_id: Option<u32>,
    pub rovi_id: Option<String>,
    pub echo_id: Option<String>,
    pub verified: i8,
    pub verified_by: Option<u32>,
    pub approved: i8,
    pub approved_by: Option<u32>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bands::Entity",
        from = "Column::BandId",
        to = "super::bands::Column::Id"
    )]
    Band,
    #[sea_orm(
        belongs_to = "super::sub_genres::Entity",
        from = "Column::SubGenreId",
        to = "super::sub_genres::Column::Id"
    )]
    SubGenre,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::VerifiedBy",
        to = "super::users::Column::Id"
    )]
    Verifier,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApprovedBy",
        to = "super::users::Column::Id"
    )]
    Approver,
    #[sea_orm(has_many = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(has_many = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(has_many = "super::radio_raw_datas::Entity")]
    RadioRawDatas,
    #[sea_orm(has_many = "super::song_aliases::Entity")]
    SongAliases,
    #[sea_orm(has_many = "super::song_performers::Entity")]
    SongPerformers,
    #[sea_orm(has_many = "super::song_rankings::Entity")]
    SongRankings,
    #[sea_orm(has_many = "super::song_total_stats::Entity")]
    SongTotalStats,
    #[sea_orm(has_many = "super::song_weekly_stats::Entity")]
    SongWeeklyStats,
    #[sea_orm(has_many = "super::temp_song_total_stats::Entity")]
    TempSongTotalStats,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(has_many = "super::albums_songs::Entity")]
    AlbumsSongs,
}

impl Related<super::albums_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsSongs.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Band.def()
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubGenre.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Approver.def()
    }
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_songs::Relation::Albums.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_songs::Relation::Songs.def().rev())
    }
}

impl Related<super::radio_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylists.def()
    }
}

impl Related<super::radio_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylistArchives.def()
    }
}

impl Related<super::radio_raw_datas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioRawDatas.def()
    }
}

impl Related<super::song_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongAliases.def()
    }
}

impl Related<super::song_performers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongPerformers.def()
    }
}

impl Related<super::song_rankings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongRankings.def()
    }
}

impl Related<super::song_total_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongTotalStats.def()
    }
}

impl Related<super::song_weekly_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongWeeklyStats.def()
    }
}

impl Related<super::temp_song_total_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TempSongTotalStats.def()
    }
}

impl Related<super::staff_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylistArchives.def()
    }
}

impl Related<super::staff_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
