//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "song_weekly_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub song_id: u32,
    pub score: i32,
    pub total_spins: i32,
    pub tw_spins: i32,
    pub lw_spins: i32,
    pub total_stations: i32,
    pub tw_stations: i32,
    pub lw_stations: i32,
    pub lw_rank: i32,
    pub weeks_on: i32,
    pub chartable: i8,
    pub week_ending: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::songs::Entity",
        from = "Column::SongId",
        to = "super::songs::Column::Id"
    )]
    Song,
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Song.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
