//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize, ToSchema)]
#[sea_orm(table_name = "staff_members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub radio_station_id: Option<u32>,
    pub user_id: Option<u32>,
    pub orig_username: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub slug: Option<String>,
    pub on_air_name: Option<String>,
    pub position: Option<String>,
    pub email: Option<String>,
    pub show_name: Option<String>,
    #[schema(value_type = Option<String>, format = "time")]
    pub start_time: Option<Time>,
    #[schema(value_type = Option<String>, format = "time")]
    pub end_time: Option<Time>,
    pub days_on: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub bio: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub show_description: Option<String>,
    pub has_playlist: i8,
    pub applied: i8,
    pub approved: i8,
    pub verified: i8,
    pub automatic: i8,
    pub playlist_finalised: i8,
    pub reported: i8,
    pub lw_reported: i8,
    pub last_reported: Option<Date>,
    pub station_control: i8,
    pub spotlight: i8,
    pub imported_from_file: i8,
    // Archive fields
    #[sea_orm(default_value = 0)]
    pub archived: i8,
    pub archived_at: Option<DateTime>,
    #[sea_orm(column_type = "String(StringLen::N(500))", nullable)]
    pub archived_reason: Option<String>,
    pub transferred_to_id: Option<u32>,
    pub transferred_from_id: Option<u32>,
    #[sea_orm(default_value = 0)]
    pub admin_editable: i8,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::radio_stations::Entity",
        from = "Column::RadioStationId",
        to = "super::radio_stations::Column::Id"
    )]
    RadioStation,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    User,
    #[sea_orm(has_many = "super::staff_addresses::Entity")]
    StaffAddresses,
    #[sea_orm(has_many = "super::staff_images::Entity")]
    StaffImages,
    #[sea_orm(has_many = "super::staff_links::Entity")]
    StaffLinks,
    #[sea_orm(has_many = "super::staff_phone_numbers::Entity")]
    StaffPhoneNumbers,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(has_many = "super::staff_member_aliases::Entity")]
    StaffMemberAliases,
    // Self-referential relations for transfer tracking
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::TransferredToId",
        to = "Column::Id"
    )]
    TransferredTo,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::TransferredFromId",
        to = "Column::Id"
    )]
    TransferredFrom,
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStation.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::staff_members_sub_genres::Relation::SubGenres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::staff_members_sub_genres::Relation::StaffMembers.def().rev())
    }
}

impl Related<super::staff_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffAddresses.def()
    }
}

impl Related<super::staff_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffImages.def()
    }
}

impl Related<super::staff_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLinks.def()
    }
}

impl Related<super::staff_phone_numbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPhoneNumbers.def()
    }
}

impl Related<super::staff_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylistArchives.def()
    }
}

impl Related<super::staff_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylists.def()
    }
}

impl Related<super::staff_member_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMemberAliases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
