//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, ToSchema)]
#[sea_orm(table_name = "staff_phone_numbers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub staff_member_id: Option<u32>,
    pub phone: Option<String>,
    pub ext: Option<i32>,
    pub r#type: Option<String>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff_members::Entity",
        from = "Column::StaffMemberId",
        to = "super::staff_members::Column::Id"
    )]
    StaffMember,
}

impl Related<super::staff_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
