//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, ToSchema)]
#[sea_orm(table_name = "staff_addresses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub staff_member_id: Option<u32>,
    pub address_1: Option<String>,
    pub address_2: Option<String>,
    pub address_3: Option<String>,
    pub attention_to: Option<String>,
    pub city_id: Option<u32>,
    pub state_id: Option<u32>,
    pub country_id: Option<u32>,
    pub postal_code_id: Option<u32>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::staff_members::Entity",
        from = "Column::StaffMemberId",
        to = "super::staff_members::Column::Id"
    )]
    StaffMember,
    #[sea_orm(
        belongs_to = "super::cities::Entity",
        from = "Column::CityId",
        to = "super::cities::Column::Id"
    )]
    City,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::Id"
    )]
    State,
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id"
    )]
    Country,
    #[sea_orm(
        belongs_to = "super::postal_codes::Entity",
        from = "Column::PostalCodeId",
        to = "super::postal_codes::Column::Id"
    )]
    PostalCode,
}

impl Related<super::staff_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMember.def()
    }
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::City.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::State.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Country.def()
    }
}

impl Related<super::postal_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostalCode.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
