//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, ToSchema)]
#[sea_orm(table_name = "states")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub country_id: Option<u32>,
    #[sea_orm(unique)]
    pub name: Option<String>,
    pub slug: Option<String>,
    pub abbrv: Option<String>,
    pub chart: i8,
    pub new: i8,
    pub correct: i8,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id"
    )]
    Country,
    #[sea_orm(has_many = "super::cities::Entity")]
    Cities,
    #[sea_orm(has_many = "super::postal_codes::Entity")]
    PostalCodes,
    #[sea_orm(has_many = "super::bands::Entity")]
    Bands,
    #[sea_orm(has_many = "super::band_changes::Entity")]
    BandChanges,
    #[sea_orm(has_many = "super::radio_addresses::Entity")]
    RadioAddresses,
    #[sea_orm(has_many = "super::staff_addresses::Entity")]
    StaffAddresses,
    #[sea_orm(has_many = "super::user_addresses::Entity")]
    UserAddresses,
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cities.def()
    }
}

impl Related<super::postal_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostalCodes.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bands.def()
    }
}

impl Related<super::band_changes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandChanges.def()
    }
}

impl Related<super::radio_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioAddresses.def()
    }
}

impl Related<super::staff_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffAddresses.def()
    }
}

impl Related<super::user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAddresses.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Country.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
