//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, ToSchema)]
#[sea_orm(table_name = "sub_genres")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub genre_id: Option<u32>,
    #[sea_orm(unique)]
    pub name: Option<String>,
    pub slug: Option<String>,
    pub chart: i8,
    pub default: i8,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::genres::Entity",
        from = "Column::GenreId",
        to = "super::genres::Column::Id"
    )]
    Genre,
    #[sea_orm(has_many = "super::songs::Entity")]
    Songs,
    #[sea_orm(has_many = "super::articles::Entity")]
    Articles,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(
        has_many = "super::albums::Entity",
        from = "Column::Id",
        to = "super::albums::Column::SubGenreForCharting"
    )]
    ChartedAlbums,
    #[sea_orm(has_many = "super::albums_sub_genres::Entity")]
    AlbumsSubGenres,
    #[sea_orm(has_many = "super::bands_sub_genres::Entity")]
    BandsSubGenres,
    #[sea_orm(has_many = "super::radio_stations_sub_genres::Entity")]
    RadioStationsSubGenres,
    #[sea_orm(has_many = "super::staff_members_sub_genres::Entity")]
    StaffMembersSubGenres,
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::staff_members::Entity> for Entity {
    fn to() -> RelationDef {
        super::staff_members_sub_genres::Relation::StaffMembers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::staff_members_sub_genres::Relation::SubGenres.def().rev())
    }
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genre.def()
    }
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_sub_genres::Relation::Albums.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_sub_genres::Relation::SubGenres.def().rev())
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_sub_genres::Relation::Bands.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_sub_genres::Relation::SubGenres.def().rev())
    }
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_sub_genres::Relation::RadioStations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::radio_stations_sub_genres::Relation::SubGenres.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
