//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "system_notes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub user_id: Option<u32>,
    pub r#type: Option<String>,
    pub title: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub description: Option<String>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    User,
    #[sea_orm(has_many = "super::roles_system_notes::Entity")]
    RolesSystemNotes,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::roles_system_notes::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::roles_system_notes::Relation::SystemNote.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
