//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "temp_album_total_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub album_id: Option<u32>,
    pub score: i32,
    pub spins: i32,
    pub tw_spins: i32,
    pub lw_spins: i32,
    pub stations: i32,
    pub tw_stations: i32,
    pub lw_stations: i32,
    pub plays: i32,
    pub downloads: i32,
    pub highest_rank: i32,
    pub highest_rank_chart: Option<String>,
    pub first_charted: Option<Date>,
    pub times_charted: i32,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id"
    )]
    Album,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Album.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
