//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "users_violations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub user_id: Option<u32>,
    pub violation_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::violations::Entity",
        from = "Column::ViolationId",
        to = "super::violations::Column::Id"
    )]
    Violation,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::violations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Violation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
