//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, ToSchema)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub role_id: u32,
    #[sea_orm(unique)]
    pub username: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub password: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub referred_by: Option<String>,
    pub promocode: Option<String>,
    pub signup_ip: Option<String>,
    pub last_login_ip: Option<String>,
    pub geo_ip_country_code: Option<String>,
    pub primary_phone: Option<String>,
    pub agreed_to_terms: i8,
    pub agreed_to_pricing: i8,
    pub activated: i8,
    pub sub_uuid: Option<String>,
    pub term: i8,
    pub pay_by_check: i8,
    pub exp: Option<Date>,
    pub radio_control: Option<i8>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RoleId",
        to = "super::roles::Column::Id"
    )]
    Role,
    #[sea_orm(has_many = "super::articles::Entity")]
    Articles,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(has_many = "super::system_notes::Entity")]
    SystemNotes,
    #[sea_orm(has_many = "super::user_addresses::Entity")]
    UserAddresses,
    #[sea_orm(has_one = "super::user_email_settings::Entity")]
    UserEmailSettings,
    #[sea_orm(has_many = "super::users_violations::Entity")]
    UsersViolations,
    #[sea_orm(has_many = "super::staff_members::Entity")]
    StaffMembers,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(
        has_many = "super::albums::Entity",
        from = "Column::Id",
        to = "super::albums::Column::ApprovedBy"
    )]
    ApprovedAlbums,
    #[sea_orm(
        has_many = "super::albums::Entity",
        from = "Column::Id",
        to = "super::albums::Column::VerifiedBy"
    )]
    VerifiedAlbums,
    #[sea_orm(
        has_many = "super::articles::Entity",
        from = "Column::Id",
        to = "super::articles::Column::ApprovedBy"
    )]
    ApprovedArticles,
    #[sea_orm(
        has_many = "super::articles::Entity",
        from = "Column::Id",
        to = "super::articles::Column::EditedBy"
    )]
    EditedArticles,
    #[sea_orm(
        has_many = "super::bands::Entity",
        from = "Column::Id",
        to = "super::bands::Column::ApprovedBy"
    )]
    ApprovedBands,
    #[sea_orm(
        has_many = "super::bands::Entity",
        from = "Column::Id",
        to = "super::bands::Column::VerifiedBy"
    )]
    VerifiedBands,
    #[sea_orm(
        has_many = "super::bands::Entity",
        from = "Column::Id",
        to = "super::bands::Column::ReviewedBy"
    )]
    ReviewedBands,
    #[sea_orm(
        has_many = "super::reviews::Entity",
        from = "Column::Id",
        to = "super::reviews::Column::ApprovedBy"
    )]
    ApprovedReviews,
    #[sea_orm(
        has_many = "super::reviews::Entity",
        from = "Column::Id",
        to = "super::reviews::Column::EditedBy"
    )]
    EditedReviews,
    #[sea_orm(
        has_many = "super::songs::Entity",
        from = "Column::Id",
        to = "super::songs::Column::ApprovedBy"
    )]
    ApprovedSongs,
    #[sea_orm(
        has_many = "super::songs::Entity",
        from = "Column::Id",
        to = "super::songs::Column::VerifiedBy"
    )]
    VerifiedSongs,
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_users::Relation::Bands.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_users::Relation::Users.def().rev())
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::system_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemNotes.def()
    }
}

impl Related<super::user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAddresses.def()
    }
}

impl Related<super::user_email_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEmailSettings.def()
    }
}

impl Related<super::users_violations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersViolations.def()
    }
}

impl Related<super::staff_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMembers.def()
    }
}

impl Related<super::staff_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylistArchives.def()
    }
}

impl Related<super::staff_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylists.def()
    }
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_users::Relation::RadioStations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::radio_stations_users::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
