//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "violations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub r#type: Option<String>,
    pub title: Option<String>,
    #[sea_orm(
        column_type = "custom(\"LONGTEXT\")",
        nullable
    )]
    pub description: Option<String>,
    pub created: Option<DateTime>,
    pub modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_violations::Entity")]
    UsersViolations,
}

impl Related<super::users_violations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersViolations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_violations::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_violations::Relation::Violation.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
