//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    pub release_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub about: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thanks: Option<String>,
    pub producer: Option<String>,
    pub engineer: Option<String>,
    pub studio: Option<String>,
    pub master: Option<String>,
    pub itunes_url: Option<String>,
    pub cdbaby_url: Option<String>,
    pub amazon_url: Option<String>,
    pub img: Option<String>,
    pub itunes_id: Option<i32>,
    pub rovi_id: Option<String>,
    pub sub_genre_for_charting: Option<i32>,
    pub genre_admin_set: Option<bool>,
    pub compilation: Option<bool>,
    pub soundtrack: Option<bool>,
    pub approved: Option<bool>,
    pub approved_by_id: Option<i32>,
    pub verified: Option<bool>,
    pub verified_by_id: Option<i32>,
    pub label_id: Option<i32>,
    #[sea_orm(has_many)]
    pub album_images: HasMany<super::album_images::Entity>,
    #[sea_orm(has_many)]
    pub album_rankings: HasMany<super::album_rankings::Entity>,
    #[sea_orm(has_many)]
    pub album_total_stats: HasMany<super::album_total_stats::Entity>,
    #[sea_orm(has_many)]
    pub album_weekly_stats: HasMany<super::album_weekly_stats::Entity>,
    #[sea_orm(
        belongs_to,
        from = "label_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub labels: HasOne<super::labels::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlist_archives: HasMany<super::radio_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlists: HasMany<super::radio_playlists::Entity>,
    #[sea_orm(has_many)]
    pub reviews: HasMany<super::reviews::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlist_archives: HasMany<super::staff_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlists: HasMany<super::staff_playlists::Entity>,
    #[sea_orm(has_many)]
    pub temp_album_total_stats: HasMany<super::temp_album_total_stats::Entity>,
    #[sea_orm(has_many, via = "albums_bands")]
    pub bands: HasMany<super::bands::Entity>,
    #[sea_orm(has_many, via = "albums_songs")]
    pub songs: HasMany<super::songs::Entity>,
    #[sea_orm(has_many, via = "albums_sub_genres")]
    pub sub_genres: HasMany<super::sub_genres::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
