//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "albums_songs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub album_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub song_id: i32,
    pub track_num: Option<i32>,
    pub disc_count: Option<i32>,
    pub disc_number: Option<i32>,
    pub track_count: Option<i32>,
    pub track_number: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "album_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub albums: HasOne<super::albums::Entity>,
    #[sea_orm(
        belongs_to,
        from = "song_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub songs: HasOne<super::songs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
