//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "articles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub category_id: i32,
    pub sub_genre_id: Option<i32>,
    pub user_id: i32,
    pub title: String,
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub approved: Option<bool>,
    pub approved_by_id: Option<i32>,
    pub edited_by_id: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub categories: HasOne<super::categories::Entity>,
    #[sea_orm(
        belongs_to,
        from = "sub_genre_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub sub_genres: HasOne<super::sub_genres::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
    #[sea_orm(has_many, via = "articles_tags")]
    pub tags: HasMany<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
