//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "band_changes")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub city_id: i32,
    pub country_id: i32,
    pub state_id: i32,
    pub name: String,
    pub slug: String,
    pub email: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "city_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub cities: HasOne<super::cities::Entity>,
    #[sea_orm(
        belongs_to,
        from = "country_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub countries: HasOne<super::countries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "state_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub states: HasOne<super::states::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
