//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "band_contacts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub band_id: i32,
    pub email: Option<String>,
    pub first_time_on_chart: Option<bool>,
    pub above_thirty: Option<bool>,
    pub above_twenty: Option<bool>,
    pub above_ten: Option<bool>,
    pub last_rank: Option<i32>,
    pub chart_rank_on: Option<i32>,
    pub dont_contact: Option<bool>,
    pub last_contacted: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "band_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub bands: HasOne<super::bands::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
