//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "bands")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    pub website: Option<String>,
    pub email: Option<String>,
    pub twitter: Option<String>,
    pub facebook_url: Option<String>,
    pub lastfm_url: Option<String>,
    pub myspace_url: Option<String>,
    pub google_url: Option<String>,
    pub wikipedia_url: Option<String>,
    pub cdbaby_url: Option<String>,
    pub youtube_url: Option<String>,
    pub reverb_url: Option<String>,
    pub itunes_url: Option<String>,
    pub instagram_url: Option<String>,
    pub pinterest_url: Option<String>,
    pub itunes_id: Option<i32>,
    pub amg_id: Option<i32>,
    pub rovi_id: Option<String>,
    pub echo_id: Option<String>,
    pub seven_digital_id: Option<i32>,
    pub discogs_id: Option<i32>,
    pub spotify_id: Option<String>,
    pub rdio_id: Option<i32>,
    pub rss_feed: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    pub verified: Option<bool>,
    pub verified_by_id: Option<i32>,
    pub approved: Option<bool>,
    pub approved_by_id: Option<i32>,
    pub reviewed_by_id: Option<i32>,
    pub hot_download: Option<bool>,
    pub city_id: Option<i32>,
    pub state_id: Option<i32>,
    pub country_id: Option<i32>,
    #[sea_orm(has_many)]
    pub band_contacts: HasMany<super::band_contacts::Entity>,
    #[sea_orm(has_many)]
    pub band_images: HasMany<super::band_images::Entity>,
    #[sea_orm(has_many)]
    pub band_links: HasMany<super::band_links::Entity>,
    #[sea_orm(
        belongs_to,
        from = "city_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub cities: HasOne<super::cities::Entity>,
    #[sea_orm(
        belongs_to,
        from = "country_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub countries: HasOne<super::countries::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlist_archives: HasMany<super::radio_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlists: HasMany<super::radio_playlists::Entity>,
    #[sea_orm(has_many)]
    pub radio_raw_datas: HasMany<super::radio_raw_datas::Entity>,
    #[sea_orm(has_many)]
    pub reviews: HasMany<super::reviews::Entity>,
    #[sea_orm(has_many)]
    pub songs: HasMany<super::songs::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlist_archives: HasMany<super::staff_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlists: HasMany<super::staff_playlists::Entity>,
    #[sea_orm(
        belongs_to,
        from = "state_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub states: HasOne<super::states::Entity>,
    #[sea_orm(has_many, via = "albums_bands")]
    pub albums: HasMany<super::albums::Entity>,
    #[sea_orm(has_many, via = "bands_sub_genres")]
    pub sub_genres: HasMany<super::sub_genres::Entity>,
    #[sea_orm(has_many, via = "bands_users")]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
