//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "band_images")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub band_id: i32,
    pub path: Option<String>,
    pub filename: Option<String>,
    pub thumbname: Option<String>,
    pub order: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "band_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub bands: HasOne<super::bands::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
