//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "countries")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub continent: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub region: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub iso_three_digit: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub iso_two_digit: Option<String>,
    pub phone_reg_exp: Option<String>,
    pub phone_format: Option<String>,
    pub phone_code: Option<String>,
    pub address_format: Option<String>,
    pub chart: Option<bool>,
    pub display_order: Option<i32>,
    #[sea_orm(has_many)]
    pub band_changes: HasMany<super::band_changes::Entity>,
    #[sea_orm(has_many)]
    pub bands: HasMany<super::bands::Entity>,
    #[sea_orm(has_many)]
    pub cities: HasMany<super::cities::Entity>,
    #[sea_orm(has_many)]
    pub postal_codes: HasMany<super::postal_codes::Entity>,
    #[sea_orm(has_many)]
    pub states: HasMany<super::states::Entity>,
    #[sea_orm(has_many)]
    pub user_addresses: HasMany<super::user_addresses::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
