//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "genres")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    pub chart: Option<bool>,
    pub display_order: Option<i32>,
    #[sea_orm(has_many)]
    pub sub_genres: HasMany<super::sub_genres::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
