//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod advertisements;
pub mod album_images;
pub mod album_rankings;
pub mod album_total_stats;
pub mod album_weekly_stats;
pub mod albums;
pub mod albums_bands;
pub mod albums_songs;
pub mod albums_sub_genres;
pub mod articles;
pub mod articles_tags;
pub mod band_changes;
pub mod band_contacts;
pub mod band_images;
pub mod band_links;
pub mod bands;
pub mod bands_sub_genres;
pub mod bands_users;
pub mod categories;
pub mod chart_functions;
pub mod cities;
pub mod countries;
pub mod genres;
pub mod labels;
pub mod postal_codes;
pub mod radio_addresses;
pub mod radio_affiliates;
pub mod radio_emails;
pub mod radio_images;
pub mod radio_internet_details;
pub mod radio_links;
pub mod radio_phone_numbers;
pub mod radio_playlist_archives;
pub mod radio_playlists;
pub mod radio_raw_datas;
pub mod radio_satellite_details;
pub mod radio_stations;
pub mod radio_stations_sub_genres;
pub mod radio_stations_users;
pub mod radio_syndicated_details;
pub mod radio_syndicated_stations;
pub mod radio_terrestrial_details;
pub mod reviews;
pub mod roles;
pub mod roles_system_notes;
pub mod song_performers;
pub mod song_rankings;
pub mod song_total_stats;
pub mod song_weekly_stats;
pub mod songs;
pub mod staff_addresses;
pub mod staff_images;
pub mod staff_links;
pub mod staff_members;
pub mod staff_phone_numbers;
pub mod staff_playlist_archives;
pub mod staff_playlists;
pub mod states;
pub mod sub_genres;
pub mod system_notes;
pub mod tags;
pub mod temp_album_total_stats;
pub mod temp_song_total_stats;
pub mod user_addresses;
pub mod user_billings;
pub mod user_email_settings;
pub mod users;
pub mod users_violations;
pub mod violations;
pub mod week_endings;

seaography::register_entity_modules!([
    advertisements,
    album_images,
    album_rankings,
    album_total_stats,
    album_weekly_stats,
    albums,
    albums_bands,
    albums_songs,
    albums_sub_genres,
    articles,
    articles_tags,
    band_changes,
    band_contacts,
    band_images,
    band_links,
    bands,
    bands_sub_genres,
    bands_users,
    categories,
    chart_functions,
    cities,
    countries,
    genres,
    labels,
    postal_codes,
    radio_addresses,
    radio_affiliates,
    radio_emails,
    radio_images,
    radio_internet_details,
    radio_links,
    radio_phone_numbers,
    radio_playlist_archives,
    radio_playlists,
    radio_raw_datas,
    radio_satellite_details,
    radio_stations,
    radio_stations_sub_genres,
    radio_stations_users,
    radio_syndicated_details,
    radio_syndicated_stations,
    radio_terrestrial_details,
    reviews,
    roles,
    roles_system_notes,
    song_performers,
    song_rankings,
    song_total_stats,
    song_weekly_stats,
    songs,
    staff_addresses,
    staff_images,
    staff_links,
    staff_members,
    staff_phone_numbers,
    staff_playlist_archives,
    staff_playlists,
    states,
    sub_genres,
    system_notes,
    tags,
    temp_album_total_stats,
    temp_song_total_stats,
    user_addresses,
    user_billings,
    user_email_settings,
    users,
    users_violations,
    violations,
    week_endings,
]);
