//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "radio_stations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    pub station_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub info: Option<String>,
    pub approved: Option<bool>,
    pub verified: Option<bool>,
    pub automatic: Option<bool>,
    pub active: Option<bool>,
    #[sea_orm(column_type = "Float", nullable)]
    pub influence: Option<f32>,
    pub no_show: Option<bool>,
    pub imported_from_file: Option<bool>,
    #[sea_orm(has_many)]
    pub radio_addresses: HasMany<super::radio_addresses::Entity>,
    #[sea_orm(has_many)]
    pub radio_affiliates: HasMany<super::radio_affiliates::Entity>,
    #[sea_orm(has_many)]
    pub radio_emails: HasMany<super::radio_emails::Entity>,
    #[sea_orm(has_many)]
    pub radio_images: HasMany<super::radio_images::Entity>,
    #[sea_orm(has_many)]
    pub radio_internet_details: HasMany<super::radio_internet_details::Entity>,
    #[sea_orm(has_many)]
    pub radio_links: HasMany<super::radio_links::Entity>,
    #[sea_orm(has_many)]
    pub radio_phone_numbers: HasMany<super::radio_phone_numbers::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlist_archives: HasMany<super::radio_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlists: HasMany<super::radio_playlists::Entity>,
    #[sea_orm(has_many)]
    pub radio_raw_datas: HasMany<super::radio_raw_datas::Entity>,
    #[sea_orm(has_many)]
    pub radio_satellite_details: HasMany<super::radio_satellite_details::Entity>,
    #[sea_orm(has_many)]
    pub radio_syndicated_details: HasMany<super::radio_syndicated_details::Entity>,
    #[sea_orm(has_many)]
    pub radio_terrestrial_details: HasMany<super::radio_terrestrial_details::Entity>,
    #[sea_orm(has_many)]
    pub staff_members: HasMany<super::staff_members::Entity>,
    #[sea_orm(has_many, via = "radio_stations_sub_genres")]
    pub sub_genres: HasMany<super::sub_genres::Entity>,
    #[sea_orm(has_many, via = "radio_stations_users")]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
