//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "radio_syndicated_stations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub radio_syndicated_detail_id: i32,
    pub call_letters: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "radio_syndicated_detail_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub radio_syndicated_details: HasOne<super::radio_syndicated_details::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
