//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "radio_playlists")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub album_id: i32,
    pub band_id: i32,
    pub radio_station_id: i32,
    pub song_id: i32,
    pub spins: i32,
    pub subtract_spins: i32,
    #[sea_orm(
        belongs_to,
        from = "album_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub albums: HasOne<super::albums::Entity>,
    #[sea_orm(
        belongs_to,
        from = "band_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub bands: HasOne<super::bands::Entity>,
    #[sea_orm(
        belongs_to,
        from = "radio_station_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub radio_stations: HasOne<super::radio_stations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "song_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub songs: HasOne<super::songs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
