//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "radio_stations_sub_genres")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub radio_station_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub sub_genre_id: i32,
    #[sea_orm(
        belongs_to,
        from = "radio_station_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub radio_stations: HasOne<super::radio_stations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "sub_genre_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub sub_genres: HasOne<super::sub_genres::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
