//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "radio_emails")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub radio_station_id: i32,
    pub email: Option<String>,
    pub email_type: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "radio_station_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub radio_stations: HasOne<super::radio_stations::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
