//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reviews")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub album_id: i32,
    pub band_id: i32,
    pub sub_genre_id: i32,
    pub user_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub review: Option<String>,
    #[sea_orm(unique)]
    pub slug: String,
    pub rating: Option<i32>,
    pub featured: Option<bool>,
    pub approved: Option<bool>,
    pub approved_by_id: Option<i32>,
    pub edited_by_id: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "album_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub albums: HasOne<super::albums::Entity>,
    #[sea_orm(
        belongs_to,
        from = "band_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub bands: HasOne<super::bands::Entity>,
    #[sea_orm(
        belongs_to,
        from = "sub_genre_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub sub_genres: HasOne<super::sub_genres::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
