//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub super_admin_access: Option<bool>,
    pub admin_access: Option<bool>,
    pub writer_access: Option<bool>,
    pub radio_access: Option<bool>,
    pub reporter_access: Option<bool>,
    pub gold_access: Option<bool>,
    pub silver_access: Option<bool>,
    pub free_access: Option<bool>,
    pub single_artist: Option<bool>,
    #[sea_orm(has_many)]
    pub users: HasMany<super::users::Entity>,
    #[sea_orm(has_many, via = "roles_system_notes")]
    pub system_notes: HasMany<super::system_notes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
