//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "roles_system_notes")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub system_note_id: i32,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub roles: HasOne<super::roles::Entity>,
    #[sea_orm(
        belongs_to,
        from = "system_note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub system_notes: HasOne<super::system_notes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
