//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "song_rankings")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub song_id: i32,
    pub category: Option<String>,
    pub chart_slug: Option<String>,
    pub term: Option<String>,
    pub limit: Option<i32>,
    pub start: Option<String>,
    pub finish: Option<String>,
    pub rank: Option<i32>,
    pub lw_rank: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "song_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub songs: HasOne<super::songs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
