//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "song_weekly_stats")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub song_id: i32,
    pub score: i32,
    pub total_spins: Option<i32>,
    pub tw_spins: Option<i32>,
    pub lw_spins: Option<i32>,
    pub total_stations: Option<i32>,
    pub tw_stations: Option<i32>,
    pub lw_stations: Option<i32>,
    pub lw_rank: Option<i32>,
    pub weeks_on: Option<i32>,
    pub chartable: Option<bool>,
    pub week_ending: Option<Date>,
    #[sea_orm(
        belongs_to,
        from = "song_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub songs: HasOne<super::songs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
