//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "songs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub lyrics: Option<String>,
    pub lyrics_writer: Option<String>,
    pub music_writer: Option<String>,
    pub license: Option<String>,
    pub publisher: Option<String>,
    pub length: Option<i64>,
    pub release_date: Option<Date>,
    pub itunes_url: Option<String>,
    pub itunes_img: Option<String>,
    pub itunes_preview: Option<String>,
    pub itunes_id: Option<i32>,
    pub rovi_id: Option<String>,
    pub echo_id: Option<String>,
    pub verified: Option<bool>,
    pub verified_by_id: Option<i32>,
    pub approved: Option<bool>,
    pub approved_by_id: Option<i32>,
    pub band_id: i32,
    pub sub_genre_id: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "band_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub bands: HasOne<super::bands::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlist_archives: HasMany<super::radio_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub radio_playlists: HasMany<super::radio_playlists::Entity>,
    #[sea_orm(has_many)]
    pub radio_raw_datas: HasMany<super::radio_raw_datas::Entity>,
    #[sea_orm(has_many)]
    pub song_performers: HasMany<super::song_performers::Entity>,
    #[sea_orm(has_many)]
    pub song_rankings: HasMany<super::song_rankings::Entity>,
    #[sea_orm(has_many)]
    pub song_total_stats: HasMany<super::song_total_stats::Entity>,
    #[sea_orm(has_many)]
    pub song_weekly_stats: HasMany<super::song_weekly_stats::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlist_archives: HasMany<super::staff_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlists: HasMany<super::staff_playlists::Entity>,
    #[sea_orm(
        belongs_to,
        from = "sub_genre_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub sub_genres: HasOne<super::sub_genres::Entity>,
    #[sea_orm(has_many)]
    pub temp_song_total_stats: HasMany<super::temp_song_total_stats::Entity>,
    #[sea_orm(has_many, via = "albums_songs")]
    pub albums: HasMany<super::albums::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
