//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "staff_playlists")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub album_id: i32,
    pub band_id: i32,
    pub song_id: i32,
    pub staff_member_id: i32,
    pub user_id: Option<i32>,
    pub spins: Option<i32>,
    pub invalid: Option<bool>,
    #[sea_orm(
        belongs_to,
        from = "album_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub albums: HasOne<super::albums::Entity>,
    #[sea_orm(
        belongs_to,
        from = "band_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub bands: HasOne<super::bands::Entity>,
    #[sea_orm(
        belongs_to,
        from = "song_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub songs: HasOne<super::songs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "staff_member_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub staff_members: HasOne<super::staff_members::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
