//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "staff_images")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub staff_member_id: i32,
    pub path: Option<String>,
    pub filename: Option<String>,
    pub thumbname: Option<String>,
    pub image_type: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "staff_member_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub staff_members: HasOne<super::staff_members::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
