//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "staff_members")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub radio_station_id: i32,
    pub user_id: i32,
    pub orig_username: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub first_name: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub last_name: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub on_air_name: Option<String>,
    pub position: Option<String>,
    pub email: Option<String>,
    pub show_name: Option<String>,
    pub start_time: Option<Time>,
    pub end_time: Option<Time>,
    pub days_on: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub show_description: Option<String>,
    pub has_playlist: Option<bool>,
    pub applied: Option<bool>,
    pub approved: Option<bool>,
    pub verified: Option<bool>,
    pub automatic: Option<bool>,
    pub playlist_finalised: Option<bool>,
    pub reported: Option<bool>,
    pub lw_reported: Option<bool>,
    pub last_reported: Option<Date>,
    pub station_control: Option<bool>,
    pub spotlight: Option<bool>,
    pub imported_from_file: Option<bool>,
    #[sea_orm(
        belongs_to,
        from = "radio_station_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub radio_stations: HasOne<super::radio_stations::Entity>,
    #[sea_orm(has_many)]
    pub staff_addresses: HasMany<super::staff_addresses::Entity>,
    #[sea_orm(has_many)]
    pub staff_images: HasMany<super::staff_images::Entity>,
    #[sea_orm(has_many)]
    pub staff_links: HasMany<super::staff_links::Entity>,
    #[sea_orm(has_many)]
    pub staff_phone_numbers: HasMany<super::staff_phone_numbers::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlist_archives: HasMany<super::staff_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlists: HasMany<super::staff_playlists::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
