//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "states")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub country_id: i32,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub slug: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"citext\")",
        select_as = "text",
        nullable
    )]
    pub abbrv: Option<String>,
    pub chart: Option<bool>,
    pub new: Option<bool>,
    pub correct: Option<bool>,
    #[sea_orm(has_many)]
    pub band_changes: HasMany<super::band_changes::Entity>,
    #[sea_orm(has_many)]
    pub bands: HasMany<super::bands::Entity>,
    #[sea_orm(has_many)]
    pub cities: HasMany<super::cities::Entity>,
    #[sea_orm(
        belongs_to,
        from = "country_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub countries: HasOne<super::countries::Entity>,
    #[sea_orm(has_many)]
    pub postal_codes: HasMany<super::postal_codes::Entity>,
    #[sea_orm(has_many)]
    pub user_addresses: HasMany<super::user_addresses::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
