//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sub_genres")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub name: String,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text")]
    pub slug: String,
    pub chart: Option<bool>,
    pub default: Option<bool>,
    pub genre_id: i32,
    #[sea_orm(has_many)]
    pub articles: HasMany<super::articles::Entity>,
    #[sea_orm(
        belongs_to,
        from = "genre_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub genres: HasOne<super::genres::Entity>,
    #[sea_orm(has_many)]
    pub reviews: HasMany<super::reviews::Entity>,
    #[sea_orm(has_many)]
    pub songs: HasMany<super::songs::Entity>,
    #[sea_orm(has_many, via = "albums_sub_genres")]
    pub albums: HasMany<super::albums::Entity>,
    #[sea_orm(has_many, via = "bands_sub_genres")]
    pub bands: HasMany<super::bands::Entity>,
    #[sea_orm(has_many, via = "radio_stations_sub_genres")]
    pub radio_stations: HasMany<super::radio_stations::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
