//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub role_id: i32,
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    #[sea_orm(unique)]
    pub api_key: String,
    pub first_name: String,
    pub last_name: String,
    pub username: String,
    pub reset_token: Option<String>,
    pub reset_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verification_token: Option<String>,
    pub email_verification_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub referred_by: Option<String>,
    pub signup_ip: Option<String>,
    pub last_login_ip: Option<String>,
    pub geo_ip_country_code: Option<String>,
    pub primary_phone: Option<String>,
    pub radio_control: Option<bool>,
    pub last_login: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub articles: HasMany<super::articles::Entity>,
    #[sea_orm(has_many)]
    pub reviews: HasMany<super::reviews::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub roles: HasOne<super::roles::Entity>,
    #[sea_orm(has_many)]
    pub staff_members: HasMany<super::staff_members::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlist_archives: HasMany<super::staff_playlist_archives::Entity>,
    #[sea_orm(has_many)]
    pub staff_playlists: HasMany<super::staff_playlists::Entity>,
    #[sea_orm(has_many)]
    pub system_notes: HasMany<super::system_notes::Entity>,
    #[sea_orm(has_many)]
    pub user_addresses: HasMany<super::user_addresses::Entity>,
    #[sea_orm(has_many)]
    pub user_billings: HasMany<super::user_billings::Entity>,
    #[sea_orm(has_many)]
    pub user_email_settings: HasMany<super::user_email_settings::Entity>,
    #[sea_orm(has_many, via = "bands_users")]
    pub bands: HasMany<super::bands::Entity>,
    #[sea_orm(has_many, via = "radio_stations_users")]
    pub radio_stations: HasMany<super::radio_stations::Entity>,
    #[sea_orm(has_many, via = "users_violations")]
    pub violations: HasMany<super::violations::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
