//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_addresses")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub address_one: Option<String>,
    pub address_two: Option<String>,
    pub address_three: Option<String>,
    pub city_id: i32,
    pub state_id: i32,
    pub country_id: i32,
    pub postal_code_id: i32,
    pub attention_to: Option<String>,
    pub user_id: i32,
    #[sea_orm(
        belongs_to,
        from = "city_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub cities: HasOne<super::cities::Entity>,
    #[sea_orm(
        belongs_to,
        from = "country_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub countries: HasOne<super::countries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "postal_code_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub postal_codes: HasOne<super::postal_codes::Entity>,
    #[sea_orm(
        belongs_to,
        from = "state_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub states: HasOne<super::states::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
