//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub slug: String,
    pub release_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub about: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thanks: Option<String>,
    pub producer: Option<String>,
    pub engineer: Option<String>,
    pub studio: Option<String>,
    pub master: Option<String>,
    pub itunes_url: Option<String>,
    pub cdbaby_url: Option<String>,
    pub amazon_url: Option<String>,
    pub img: Option<String>,
    pub itunes_id: Option<i32>,
    pub rovi_id: Option<String>,
    pub sub_genre_for_charting: Option<i32>,
    pub genre_admin_set: Option<bool>,
    pub compilation: Option<bool>,
    pub soundtrack: Option<bool>,
    pub approved: Option<bool>,
    pub approved_by: Option<i32>,
    pub verified: Option<bool>,
    pub verified_by: Option<i32>,
    pub label_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_images::Entity")]
    AlbumImages,
    #[sea_orm(has_many = "super::album_rankings::Entity")]
    AlbumRankings,
    #[sea_orm(has_many = "super::album_total_stats::Entity")]
    AlbumTotalStats,
    #[sea_orm(has_many = "super::album_weekly_stats::Entity")]
    AlbumWeeklyStats,
    #[sea_orm(has_many = "super::albums_bands::Entity")]
    AlbumsBands,
    #[sea_orm(has_many = "super::albums_songs::Entity")]
    AlbumsSongs,
    #[sea_orm(has_many = "super::albums_sub_genres::Entity")]
    AlbumsSubGenres,
    #[sea_orm(
        belongs_to = "super::labels::Entity",
        from = "Column::LabelId",
        to = "super::labels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Labels,
    #[sea_orm(has_many = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(has_many = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(has_many = "super::temp_album_total_stats::Entity")]
    TempAlbumTotalStats,
}

impl Related<super::album_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumImages.def()
    }
}

impl Related<super::album_rankings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumRankings.def()
    }
}

impl Related<super::album_total_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumTotalStats.def()
    }
}

impl Related<super::album_weekly_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumWeeklyStats.def()
    }
}

impl Related<super::albums_bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsBands.def()
    }
}

impl Related<super::albums_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsSongs.def()
    }
}

impl Related<super::albums_sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsSubGenres.def()
    }
}

impl Related<super::labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Labels.def()
    }
}

impl Related<super::radio_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylistArchives.def()
    }
}

impl Related<super::radio_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylists.def()
    }
}

impl Related<super::staff_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylistArchives.def()
    }
}

impl Related<super::staff_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylists.def()
    }
}

impl Related<super::temp_album_total_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TempAlbumTotalStats.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_bands::Relation::Bands.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_bands::Relation::Albums.def().rev())
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_songs::Relation::Songs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_songs::Relation::Albums.def().rev())
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_sub_genres::Relation::SubGenres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_sub_genres::Relation::Albums.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::album_images::Entity")]
    AlbumImages,
    #[sea_orm(entity = "super::album_rankings::Entity")]
    AlbumRankings,
    #[sea_orm(entity = "super::album_total_stats::Entity")]
    AlbumTotalStats,
    #[sea_orm(entity = "super::album_weekly_stats::Entity")]
    AlbumWeeklyStats,
    #[sea_orm(entity = "super::albums_bands::Entity")]
    AlbumsBands,
    #[sea_orm(entity = "super::albums_songs::Entity")]
    AlbumsSongs,
    #[sea_orm(entity = "super::albums_sub_genres::Entity")]
    AlbumsSubGenres,
    #[sea_orm(entity = "super::labels::Entity")]
    Labels,
    #[sea_orm(entity = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(entity = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(entity = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(entity = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(entity = "super::temp_album_total_stats::Entity")]
    TempAlbumTotalStats,
    #[sea_orm(entity = "super::bands::Entity")]
    Bands,
    #[sea_orm(entity = "super::songs::Entity")]
    Songs,
    #[sea_orm(entity = "super::sub_genres::Entity")]
    SubGenres,
}
