//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "album_total_stats")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub album_id: i32,
    pub score: i32,
    pub spins: i32,
    pub tw_spins: Option<i32>,
    pub lw_spins: Option<i32>,
    pub stations: i32,
    pub tw_stations: Option<i32>,
    pub lw_stations: Option<i32>,
    pub plays: Option<i32>,
    pub downloads: Option<i32>,
    pub highest_rank: Option<i32>,
    pub highest_rank_chart: Option<String>,
    pub first_charted: Option<Date>,
    pub times_charted: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Albums,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Albums.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::albums::Entity")]
    Albums,
}
