//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "articles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub category_id: i32,
    pub sub_genre_id: Option<i32>,
    pub user_id: i32,
    pub title: String,
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub approved: Option<bool>,
    pub approved_by: Option<i32>,
    pub edited_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::articles_tags::Entity")]
    ArticlesTags,
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Categories,
    #[sea_orm(
        belongs_to = "super::sub_genres::Entity",
        from = "Column::SubGenreId",
        to = "super::sub_genres::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SubGenres,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::articles_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticlesTags.def()
    }
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubGenres.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::articles_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::articles_tags::Relation::Articles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::articles_tags::Entity")]
    ArticlesTags,
    #[sea_orm(entity = "super::categories::Entity")]
    Categories,
    #[sea_orm(entity = "super::sub_genres::Entity")]
    SubGenres,
    #[sea_orm(entity = "super::users::Entity")]
    Users,
    #[sea_orm(entity = "super::tags::Entity")]
    Tags,
}
