//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "bands")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub slug: String,
    pub website: Option<String>,
    pub email: Option<String>,
    pub twitter: Option<String>,
    pub facebook_url: Option<String>,
    pub lastfm_url: Option<String>,
    pub myspace_url: Option<String>,
    pub google_url: Option<String>,
    pub wikipedia_url: Option<String>,
    pub cdbaby_url: Option<String>,
    pub youtube_url: Option<String>,
    pub reverb_url: Option<String>,
    pub itunes_url: Option<String>,
    pub instagram_url: Option<String>,
    pub pinterest_url: Option<String>,
    pub itunes_id: Option<i32>,
    pub amg_id: Option<i32>,
    pub rovi_id: Option<String>,
    pub echo_id: Option<String>,
    pub seven_digital_id: Option<i32>,
    pub discogs_id: Option<i32>,
    pub spotify_id: Option<String>,
    pub rdio_id: Option<i32>,
    pub rss_feed: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    pub verified: Option<bool>,
    pub verified_by: Option<i32>,
    pub approved: Option<bool>,
    pub approved_by: Option<i32>,
    pub reviewed_by: Option<i32>,
    pub hot_download: Option<bool>,
    pub city_id: Option<i32>,
    pub state_id: Option<i32>,
    pub country_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::albums_bands::Entity")]
    AlbumsBands,
    #[sea_orm(has_many = "super::band_contacts::Entity")]
    BandContacts,
    #[sea_orm(has_many = "super::band_images::Entity")]
    BandImages,
    #[sea_orm(has_many = "super::band_links::Entity")]
    BandLinks,
    #[sea_orm(has_many = "super::bands_sub_genres::Entity")]
    BandsSubGenres,
    #[sea_orm(has_many = "super::bands_users::Entity")]
    BandsUsers,
    #[sea_orm(
        belongs_to = "super::cities::Entity",
        from = "Column::CityId",
        to = "super::cities::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cities,
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Countries,
    #[sea_orm(has_many = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(has_many = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(has_many = "super::radio_raw_datas::Entity")]
    RadioRawDatas,
    #[sea_orm(has_many = "super::songs::Entity")]
    Songs,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    States,
}

impl Related<super::albums_bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsBands.def()
    }
}

impl Related<super::band_contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandContacts.def()
    }
}

impl Related<super::band_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandImages.def()
    }
}

impl Related<super::band_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandLinks.def()
    }
}

impl Related<super::bands_sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandsSubGenres.def()
    }
}

impl Related<super::bands_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandsUsers.def()
    }
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cities.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::radio_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylistArchives.def()
    }
}

impl Related<super::radio_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylists.def()
    }
}

impl Related<super::radio_raw_datas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioRawDatas.def()
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl Related<super::staff_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylistArchives.def()
    }
}

impl Related<super::staff_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylists.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_bands::Relation::Albums.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_bands::Relation::Bands.def().rev())
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_sub_genres::Relation::SubGenres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_sub_genres::Relation::Bands.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_users::Relation::Bands.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::albums_bands::Entity")]
    AlbumsBands,
    #[sea_orm(entity = "super::band_contacts::Entity")]
    BandContacts,
    #[sea_orm(entity = "super::band_images::Entity")]
    BandImages,
    #[sea_orm(entity = "super::band_links::Entity")]
    BandLinks,
    #[sea_orm(entity = "super::bands_sub_genres::Entity")]
    BandsSubGenres,
    #[sea_orm(entity = "super::bands_users::Entity")]
    BandsUsers,
    #[sea_orm(entity = "super::cities::Entity")]
    Cities,
    #[sea_orm(entity = "super::countries::Entity")]
    Countries,
    #[sea_orm(entity = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(entity = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(entity = "super::radio_raw_datas::Entity")]
    RadioRawDatas,
    #[sea_orm(entity = "super::songs::Entity")]
    Songs,
    #[sea_orm(entity = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(entity = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(entity = "super::states::Entity")]
    States,
    #[sea_orm(entity = "super::albums::Entity")]
    Albums,
    #[sea_orm(entity = "super::sub_genres::Entity")]
    SubGenres,
    #[sea_orm(entity = "super::users::Entity")]
    Users,
}
