//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "countries")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub slug: String,
    pub continent: Option<String>,
    pub region: Option<String>,
    pub iso_three_digit: Option<String>,
    pub iso_two_digit: Option<String>,
    pub phone_reg_exp: Option<String>,
    pub phone_format: Option<String>,
    pub phone_code: Option<String>,
    pub address_format: Option<String>,
    pub chart: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::band_changes::Entity")]
    BandChanges,
    #[sea_orm(has_many = "super::bands::Entity")]
    Bands,
    #[sea_orm(has_many = "super::cities::Entity")]
    Cities,
    #[sea_orm(has_many = "super::postal_codes::Entity")]
    PostalCodes,
    #[sea_orm(has_many = "super::states::Entity")]
    States,
    #[sea_orm(has_many = "super::user_addresses::Entity")]
    UserAddresses,
}

impl Related<super::band_changes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandChanges.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bands.def()
    }
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cities.def()
    }
}

impl Related<super::postal_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostalCodes.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl Related<super::user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAddresses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::band_changes::Entity")]
    BandChanges,
    #[sea_orm(entity = "super::bands::Entity")]
    Bands,
    #[sea_orm(entity = "super::cities::Entity")]
    Cities,
    #[sea_orm(entity = "super::postal_codes::Entity")]
    PostalCodes,
    #[sea_orm(entity = "super::states::Entity")]
    States,
    #[sea_orm(entity = "super::user_addresses::Entity")]
    UserAddresses,
}
