//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "postal_codes")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub country_id: i32,
    pub state_id: Option<i32>,
    pub code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Countries,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    States,
    #[sea_orm(has_many = "super::user_addresses::Entity")]
    UserAddresses,
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl Related<super::user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAddresses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::countries::Entity")]
    Countries,
    #[sea_orm(entity = "super::states::Entity")]
    States,
    #[sea_orm(entity = "super::user_addresses::Entity")]
    UserAddresses,
}
