//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "radio_stations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub slug: String,
    pub station_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub info: Option<String>,
    pub approved: Option<bool>,
    pub verified: Option<bool>,
    pub automatic: Option<bool>,
    pub active: Option<bool>,
    #[sea_orm(column_type = "Float", nullable)]
    pub influence: Option<f32>,
    pub no_show: Option<bool>,
    pub imported_from_file: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::radio_addresses::Entity")]
    RadioAddresses,
    #[sea_orm(has_many = "super::radio_affiliates::Entity")]
    RadioAffiliates,
    #[sea_orm(has_many = "super::radio_emails::Entity")]
    RadioEmails,
    #[sea_orm(has_many = "super::radio_images::Entity")]
    RadioImages,
    #[sea_orm(has_many = "super::radio_internet_details::Entity")]
    RadioInternetDetails,
    #[sea_orm(has_many = "super::radio_links::Entity")]
    RadioLinks,
    #[sea_orm(has_many = "super::radio_phone_numbers::Entity")]
    RadioPhoneNumbers,
    #[sea_orm(has_many = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(has_many = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(has_many = "super::radio_raw_datas::Entity")]
    RadioRawDatas,
    #[sea_orm(has_many = "super::radio_satellite_details::Entity")]
    RadioSatelliteDetails,
    #[sea_orm(has_many = "super::radio_stations_sub_genres::Entity")]
    RadioStationsSubGenres,
    #[sea_orm(has_many = "super::radio_stations_users::Entity")]
    RadioStationsUsers,
    #[sea_orm(has_many = "super::radio_syndicated_details::Entity")]
    RadioSyndicatedDetails,
    #[sea_orm(has_many = "super::radio_terrestrial_details::Entity")]
    RadioTerrestrialDetails,
    #[sea_orm(has_many = "super::staff_members::Entity")]
    StaffMembers,
}

impl Related<super::radio_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioAddresses.def()
    }
}

impl Related<super::radio_affiliates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioAffiliates.def()
    }
}

impl Related<super::radio_emails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioEmails.def()
    }
}

impl Related<super::radio_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioImages.def()
    }
}

impl Related<super::radio_internet_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioInternetDetails.def()
    }
}

impl Related<super::radio_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioLinks.def()
    }
}

impl Related<super::radio_phone_numbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPhoneNumbers.def()
    }
}

impl Related<super::radio_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylistArchives.def()
    }
}

impl Related<super::radio_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioPlaylists.def()
    }
}

impl Related<super::radio_raw_datas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioRawDatas.def()
    }
}

impl Related<super::radio_satellite_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioSatelliteDetails.def()
    }
}

impl Related<super::radio_stations_sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStationsSubGenres.def()
    }
}

impl Related<super::radio_stations_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStationsUsers.def()
    }
}

impl Related<super::radio_syndicated_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioSyndicatedDetails.def()
    }
}

impl Related<super::radio_terrestrial_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioTerrestrialDetails.def()
    }
}

impl Related<super::staff_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMembers.def()
    }
}

impl Related<super::sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_sub_genres::Relation::SubGenres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::radio_stations_sub_genres::Relation::RadioStations
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::radio_stations_users::Relation::RadioStations
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::radio_addresses::Entity")]
    RadioAddresses,
    #[sea_orm(entity = "super::radio_affiliates::Entity")]
    RadioAffiliates,
    #[sea_orm(entity = "super::radio_emails::Entity")]
    RadioEmails,
    #[sea_orm(entity = "super::radio_images::Entity")]
    RadioImages,
    #[sea_orm(entity = "super::radio_internet_details::Entity")]
    RadioInternetDetails,
    #[sea_orm(entity = "super::radio_links::Entity")]
    RadioLinks,
    #[sea_orm(entity = "super::radio_phone_numbers::Entity")]
    RadioPhoneNumbers,
    #[sea_orm(entity = "super::radio_playlist_archives::Entity")]
    RadioPlaylistArchives,
    #[sea_orm(entity = "super::radio_playlists::Entity")]
    RadioPlaylists,
    #[sea_orm(entity = "super::radio_raw_datas::Entity")]
    RadioRawDatas,
    #[sea_orm(entity = "super::radio_satellite_details::Entity")]
    RadioSatelliteDetails,
    #[sea_orm(entity = "super::radio_stations_sub_genres::Entity")]
    RadioStationsSubGenres,
    #[sea_orm(entity = "super::radio_stations_users::Entity")]
    RadioStationsUsers,
    #[sea_orm(entity = "super::radio_syndicated_details::Entity")]
    RadioSyndicatedDetails,
    #[sea_orm(entity = "super::radio_terrestrial_details::Entity")]
    RadioTerrestrialDetails,
    #[sea_orm(entity = "super::staff_members::Entity")]
    StaffMembers,
    #[sea_orm(entity = "super::sub_genres::Entity")]
    SubGenres,
    #[sea_orm(entity = "super::users::Entity")]
    Users,
}
