//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "radio_syndicated_stations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub radio_syndicated_detail_id: i32,
    pub call_letters: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::radio_syndicated_details::Entity",
        from = "Column::RadioSyndicatedDetailId",
        to = "super::radio_syndicated_details::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RadioSyndicatedDetails,
}

impl Related<super::radio_syndicated_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioSyndicatedDetails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::radio_syndicated_details::Entity")]
    RadioSyndicatedDetails,
}
