//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub super_admin_access: Option<bool>,
    pub admin_access: Option<bool>,
    pub writer_access: Option<bool>,
    pub radio_access: Option<bool>,
    pub reporter_access: Option<bool>,
    pub gold_access: Option<bool>,
    pub silver_access: Option<bool>,
    pub free_access: Option<bool>,
    pub single_artist: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::roles_system_notes::Entity")]
    RolesSystemNotes,
}

impl Related<super::roles_system_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolesSystemNotes.def()
    }
}

impl Related<super::system_notes::Entity> for Entity {
    fn to() -> RelationDef {
        super::roles_system_notes::Relation::SystemNotes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::roles_system_notes::Relation::Roles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::roles_system_notes::Entity")]
    RolesSystemNotes,
    #[sea_orm(entity = "super::system_notes::Entity")]
    SystemNotes,
}
