//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "staff_members")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub radio_station_id: i32,
    pub user_id: i32,
    pub orig_username: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub slug: String,
    pub on_air_name: Option<String>,
    pub position: Option<String>,
    pub email: Option<String>,
    pub show_name: Option<String>,
    pub start_time: Option<Time>,
    pub end_time: Option<Time>,
    pub days_on: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub show_description: Option<String>,
    pub has_playlist: Option<bool>,
    pub applied: Option<bool>,
    pub approved: Option<bool>,
    pub verified: Option<bool>,
    pub automatic: Option<bool>,
    pub playlist_finalised: Option<bool>,
    pub reported: Option<bool>,
    pub lw_reported: Option<bool>,
    pub last_reported: Option<Date>,
    pub station_control: Option<bool>,
    pub spotlight: Option<bool>,
    pub imported_from_file: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::radio_stations::Entity",
        from = "Column::RadioStationId",
        to = "super::radio_stations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RadioStations,
    #[sea_orm(has_many = "super::staff_addresses::Entity")]
    StaffAddresses,
    #[sea_orm(has_many = "super::staff_images::Entity")]
    StaffImages,
    #[sea_orm(has_many = "super::staff_links::Entity")]
    StaffLinks,
    #[sea_orm(has_many = "super::staff_phone_numbers::Entity")]
    StaffPhoneNumbers,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStations.def()
    }
}

impl Related<super::staff_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffAddresses.def()
    }
}

impl Related<super::staff_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffImages.def()
    }
}

impl Related<super::staff_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffLinks.def()
    }
}

impl Related<super::staff_phone_numbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPhoneNumbers.def()
    }
}

impl Related<super::staff_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylistArchives.def()
    }
}

impl Related<super::staff_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylists.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::radio_stations::Entity")]
    RadioStations,
    #[sea_orm(entity = "super::staff_addresses::Entity")]
    StaffAddresses,
    #[sea_orm(entity = "super::staff_images::Entity")]
    StaffImages,
    #[sea_orm(entity = "super::staff_links::Entity")]
    StaffLinks,
    #[sea_orm(entity = "super::staff_phone_numbers::Entity")]
    StaffPhoneNumbers,
    #[sea_orm(entity = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(entity = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(entity = "super::users::Entity")]
    Users,
}
