//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sub_genres")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub slug: String,
    pub chart: Option<bool>,
    pub default: Option<bool>,
    pub genre_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::albums_sub_genres::Entity")]
    AlbumsSubGenres,
    #[sea_orm(has_many = "super::articles::Entity")]
    Articles,
    #[sea_orm(has_many = "super::bands_sub_genres::Entity")]
    BandsSubGenres,
    #[sea_orm(
        belongs_to = "super::genres::Entity",
        from = "Column::GenreId",
        to = "super::genres::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Genres,
    #[sea_orm(has_many = "super::radio_stations_sub_genres::Entity")]
    RadioStationsSubGenres,
    #[sea_orm(has_many = "super::songs::Entity")]
    Songs,
}

impl Related<super::albums_sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsSubGenres.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl Related<super::bands_sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandsSubGenres.def()
    }
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genres.def()
    }
}

impl Related<super::radio_stations_sub_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStationsSubGenres.def()
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_sub_genres::Relation::Albums.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::albums_sub_genres::Relation::SubGenres.def().rev())
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_sub_genres::Relation::Bands.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_sub_genres::Relation::SubGenres.def().rev())
    }
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_sub_genres::Relation::RadioStations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::radio_stations_sub_genres::Relation::SubGenres
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::albums_sub_genres::Entity")]
    AlbumsSubGenres,
    #[sea_orm(entity = "super::articles::Entity")]
    Articles,
    #[sea_orm(entity = "super::bands_sub_genres::Entity")]
    BandsSubGenres,
    #[sea_orm(entity = "super::genres::Entity")]
    Genres,
    #[sea_orm(entity = "super::radio_stations_sub_genres::Entity")]
    RadioStationsSubGenres,
    #[sea_orm(entity = "super::songs::Entity")]
    Songs,
    #[sea_orm(entity = "super::albums::Entity")]
    Albums,
    #[sea_orm(entity = "super::bands::Entity")]
    Bands,
    #[sea_orm(entity = "super::radio_stations::Entity")]
    RadioStations,
}
