//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub slug: String,
    pub count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::articles_tags::Entity")]
    ArticlesTags,
}

impl Related<super::articles_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticlesTags.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        super::articles_tags::Relation::Articles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::articles_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::articles_tags::Entity")]
    ArticlesTags,
    #[sea_orm(entity = "super::articles::Entity")]
    Articles,
}
