//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub role_id: i32,
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    #[sea_orm(unique)]
    pub api_key: String,
    pub name: String,
    pub reset_token: Option<String>,
    pub reset_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verification_token: Option<String>,
    pub email_verification_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub referred_by: Option<String>,
    pub signup_ip: Option<String>,
    pub last_login_ip: Option<String>,
    pub geo_ip_country_code: Option<String>,
    pub primary_phone: Option<String>,
    pub radio_control: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::articles::Entity")]
    Articles,
    #[sea_orm(has_many = "super::bands_users::Entity")]
    BandsUsers,
    #[sea_orm(has_many = "super::radio_stations_users::Entity")]
    RadioStationsUsers,
    #[sea_orm(has_many = "super::staff_members::Entity")]
    StaffMembers,
    #[sea_orm(has_many = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(has_many = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(has_many = "super::system_notes::Entity")]
    SystemNotes,
    #[sea_orm(has_many = "super::user_addresses::Entity")]
    UserAddresses,
    #[sea_orm(has_many = "super::user_billings::Entity")]
    UserBillings,
    #[sea_orm(has_many = "super::user_email_settings::Entity")]
    UserEmailSettings,
    #[sea_orm(has_many = "super::users_violations::Entity")]
    UsersViolations,
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl Related<super::bands_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandsUsers.def()
    }
}

impl Related<super::radio_stations_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RadioStationsUsers.def()
    }
}

impl Related<super::staff_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffMembers.def()
    }
}

impl Related<super::staff_playlist_archives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylistArchives.def()
    }
}

impl Related<super::staff_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaffPlaylists.def()
    }
}

impl Related<super::system_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemNotes.def()
    }
}

impl Related<super::user_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAddresses.def()
    }
}

impl Related<super::user_billings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserBillings.def()
    }
}

impl Related<super::user_email_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEmailSettings.def()
    }
}

impl Related<super::users_violations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersViolations.def()
    }
}

impl Related<super::bands::Entity> for Entity {
    fn to() -> RelationDef {
        super::bands_users::Relation::Bands.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bands_users::Relation::Users.def().rev())
    }
}

impl Related<super::radio_stations::Entity> for Entity {
    fn to() -> RelationDef {
        super::radio_stations_users::Relation::RadioStations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::radio_stations_users::Relation::Users.def().rev())
    }
}

impl Related<super::violations::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_violations::Relation::Violations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_violations::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::articles::Entity")]
    Articles,
    #[sea_orm(entity = "super::bands_users::Entity")]
    BandsUsers,
    #[sea_orm(entity = "super::radio_stations_users::Entity")]
    RadioStationsUsers,
    #[sea_orm(entity = "super::staff_members::Entity")]
    StaffMembers,
    #[sea_orm(entity = "super::staff_playlist_archives::Entity")]
    StaffPlaylistArchives,
    #[sea_orm(entity = "super::staff_playlists::Entity")]
    StaffPlaylists,
    #[sea_orm(entity = "super::system_notes::Entity")]
    SystemNotes,
    #[sea_orm(entity = "super::user_addresses::Entity")]
    UserAddresses,
    #[sea_orm(entity = "super::user_billings::Entity")]
    UserBillings,
    #[sea_orm(entity = "super::user_email_settings::Entity")]
    UserEmailSettings,
    #[sea_orm(entity = "super::users_violations::Entity")]
    UsersViolations,
    #[sea_orm(entity = "super::bands::Entity")]
    Bands,
    #[sea_orm(entity = "super::radio_stations::Entity")]
    RadioStations,
    #[sea_orm(entity = "super::violations::Entity")]
    Violations,
}
